#! /usr/bin/env python3
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 8.1
#  in conjunction with Tcl version 8.6
#    Jan 19, 2026 05:49:54 PM CET  platform: Windows NT

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *
import os.path

_location = os.path.dirname(__file__)

import GUI_support

_bgcolor = '#d9d9d9'
_fgcolor = '#000000'
_tabfg1 = 'black' 
_tabfg2 = 'white' 
_bgmode = 'light' 
_tabbg1 = '#d9d9d9' 
_tabbg2 = 'gray40' 

_style_code_ran = 0
def _style_code():
    global _style_code_ran
    if _style_code_ran: return        
    try: GUI_support.root.tk.call('source',
                os.path.join(_location, 'themes', 'default.tcl'))
    except: pass
    style = ttk.Style()
    style.theme_use('default')
    style.configure('.', font = "TkDefaultFont")
    if sys.platform == "win32":
       style.theme_use('winnative')    
    _style_code_ran = 1

class FrameBP:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''

        top.geometry("1440x829+-7+0")
        top.minsize(120, 1)
        top.maxsize(1444, 881)
        top.resizable(1,  1)
        top.title("Toplevel 0")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="#000000")

        self.top = top
        self.combobox = tk.StringVar()
        self.combobox.set('TCombobox')
        self.tch65 = tk.IntVar()
        self.tch66 = tk.IntVar()
        self.tch69 = tk.IntVar()
        self.tch67 = tk.IntVar()
        self.tch68 = tk.IntVar()
        self.tch70 = tk.IntVar()

        self.BackgroundStudent = tk.Frame(self.top)
        self.BackgroundStudent.place(relx=0.0, rely=0.0, relheight=1.006
                , relwidth=1.003)
        self.BackgroundStudent.configure(relief='groove', borderwidth="2",
                background="#c8102e", highlightbackground="#c8102e",
                highlightcolor="#c8102e")

        self.FrameMenuBar = tk.Frame(self.BackgroundStudent)
        self.FrameMenuBar.place(relx=0.0, rely=0.0, relheight=0.042
                , relwidth=1.001)
        self.FrameMenuBar.configure(relief='groove', borderwidth="2",
                background="#d9d9d9", highlightbackground="#d9d9d9",
                highlightcolor="#000000")

        self.StudentHelpButton = tk.Button(self.FrameMenuBar)
        self.StudentHelpButton.place(relx=0.902, rely=0.143, height=26, width=47)
        self.StudentHelpButton.configure(activebackground="#d9d9d9",
                activeforeground="black", background="#d9d9d9",
                compound='left', cursor="fleur", disabledforeground="#a3a3a3",
                foreground="white", highlightbackground="#d9d9d9",
                highlightcolor="#000000", text='''Help''')

        self.StudentExportButton = tk.Button(self.FrameMenuBar)
        self.StudentExportButton.place(relx=0.947, rely=0.143, height=26
                , width=47)
        self.StudentExportButton.configure(activebackground="#d9d9d9",
                activeforeground="black", background="#d9d9d9",
                compound='left', disabledforeground="#a3a3a3",
                foreground="white", highlightbackground="#d9d9d9",
                highlightcolor="#000000", text='''Export''')

        self.StudentLogoutButton = tk.Button(self.FrameMenuBar)
        self.StudentLogoutButton.place(relx=0.013, rely=0.143, height=26
                , width=47)
        self.StudentLogoutButton.configure(activebackground="#d9d9d9",
                activeforeground="black", background="#d9d9d9",
                compound='left', disabledforeground="#a3a3a3",
                foreground="white", highlightbackground="#d9d9d9",
                highlightcolor="#000000", text='''Log out''')

        self.FrameLP = tk.Frame(self.BackgroundStudent)
        self.FrameLP.place(relx=0.014, rely=0.06, relheight=0.904
                , relwidth=0.296)
        self.FrameLP.configure(relief='groove', borderwidth="2",
                background="#d9d9d9", highlightbackground="#d9d9d9",
                highlightcolor="#000000")

        _style_code()
        self.EntryGradeLP = ttk.Entry(self.FrameLP)
        self.EntryGradeLP.place(relx=0.164, rely=0.106, relheight=0.028
                , relwidth=0.785)
        self.EntryGradeLP.configure(exportselection="0")
        self.EntryGradeLP.configure(cursor="ibeam")

        self.MenuLanguagesLP = ttk.Combobox(self.FrameLP)
        self.MenuLanguagesLP.place(relx=0.07, rely=0.225, relheight=0.025
                , relwidth=0.343)
        self.MenuLanguagesLP.configure(exportselection="0")
        self.MenuLanguagesLP.configure(textvariable=self.combobox)

        self.FrameLanguagesLP = tk.Frame(self.FrameLP)
        self.FrameLanguagesLP.place(relx=0.07, rely=0.265, relheight=0.179
                , relwidth=0.855)
        self.FrameLanguagesLP.configure(relief='groove', borderwidth="2",
                background="#d9d9d9", highlightbackground="#d9d9d9",
                highlightcolor="#000000")

        self.Separator1LP = ttk.Separator(self.FrameLP)
        self.Separator1LP.place(relx=0.058, rely=0.164,  relwidth=0.886)

        self.Separator2LP = ttk.Separator(self.FrameLP)
        self.Separator2LP.place(relx=0.061, rely=0.584,  relwidth=0.876)

        self.LabelTitleLP = tk.Label(self.FrameLP)
        self.LabelTitleLP.place(relx=0.07, rely=0.027, height=21, width=64)
        self.LabelTitleLP.configure(activebackground="#d9d9d9",
                activeforeground="black", anchor='w', background="#d9d9d9",
                compound='left', disabledforeground="#a3a3a3",
                foreground="white", highlightbackground="#d9d9d9",
                highlightcolor="#000000", text='''Student''')

        self.MenuDegreeLP = ttk.Combobox(self.FrameLP)
        self.MenuDegreeLP.place(relx=0.21, rely=0.066, relheight=0.025
                , relwidth=0.743)
        self.MenuDegreeLP.configure(exportselection="0")
        self.MenuDegreeLP.configure(textvariable=self.combobox)

        self.LabelDegreeLP = tk.Label(self.FrameLP)
        self.LabelDegreeLP.place(relx=0.07, rely=0.066, height=21, width=54)
        self.LabelDegreeLP.configure(activebackground="#d9d9d9",
                activeforeground="black", anchor='w', background="#d9d9d9",
                compound='left', disabledforeground="#a3a3a3",
                foreground="white", highlightbackground="#d9d9d9",
                highlightcolor="#000000", text='''Degree''')

        self.LabelGradeLP = tk.Label(self.FrameLP)
        self.LabelGradeLP.place(relx=0.07, rely=0.106, height=21, width=34)
        self.LabelGradeLP.configure(activebackground="#d9d9d9",
                activeforeground="black", anchor='w', background="#d9d9d9",
                compound='left', disabledforeground="#a3a3a3",
                foreground="white", highlightbackground="#d9d9d9",
                highlightcolor="#000000", text='''Grade''')

        self.LabelLanguagesLP = tk.Label(self.FrameLP)
        self.LabelLanguagesLP.place(relx=0.07, rely=0.184, height=22, width=74)
        self.LabelLanguagesLP.configure(activebackground="#d9d9d9",
                activeforeground="black", anchor='w', background="#d9d9d9",
                compound='left', disabledforeground="#a3a3a3",
                foreground="white", highlightbackground="#d9d9d9",
                highlightcolor="#000000", text='''Languages''')

        self.ButtonAddLanguageLP = ttk.Button(self.FrameLP)
        self.ButtonAddLanguageLP.place(relx=0.444, rely=0.221, height=26
                , width=65)
        self.ButtonAddLanguageLP.configure(text='''Add''')
        self.ButtonAddLanguageLP.configure(compound='left')

        self.LabelContinentsLP = tk.Label(self.FrameLP)
        self.LabelContinentsLP.place(relx=0.07, rely=0.464, height=21, width=84)
        self.LabelContinentsLP.configure(activebackground="#d9d9d9",
                activeforeground="black", anchor='w', background="#d9d9d9",
                compound='left', disabledforeground="#a3a3a3",
                foreground="white", highlightbackground="#d9d9d9",
                highlightcolor="#000000", text='''Continents''')

        self.CheckEuropeLP = ttk.Checkbutton(self.FrameLP)
        self.CheckEuropeLP.place(relx=0.093, rely=0.503, relwidth=0.131
                , relheight=0.0, height=19)
        self.CheckEuropeLP.configure(variable=self.tch65)
        self.CheckEuropeLP.configure(text='''Europe''')
        self.CheckEuropeLP.configure(compound='left')

        self.CheckSouthAmericaLP = ttk.Checkbutton(self.FrameLP)
        self.CheckSouthAmericaLP.place(relx=0.376, rely=0.503, relwidth=0.245
                , relheight=0.0, height=19)
        self.CheckSouthAmericaLP.configure(variable=self.tch66)
        self.CheckSouthAmericaLP.configure(text='''North America''')
        self.CheckSouthAmericaLP.configure(compound='left')

        self.CheckAsiaLP = ttk.Checkbutton(self.FrameLP)
        self.CheckAsiaLP.place(relx=0.657, rely=0.503, relwidth=0.245
                , relheight=0.0, height=19)
        self.CheckAsiaLP.configure(variable=self.tch69)
        self.CheckAsiaLP.configure(text='''South America''')
        self.CheckAsiaLP.configure(compound='left')
        self.CheckAsiaLP.configure(cursor="fleur")

        self.CheckAfricaLP = ttk.Checkbutton(self.FrameLP)
        self.CheckAfricaLP.place(relx=0.093, rely=0.531, relwidth=0.131
                , relheight=0.0, height=18)
        self.CheckAfricaLP.configure(variable=self.tch67)
        self.CheckAfricaLP.configure(text='''Asia''')
        self.CheckAfricaLP.configure(compound='left')

        self.CheckNorthAmericaLP = ttk.Checkbutton(self.FrameLP)
        self.CheckNorthAmericaLP.place(relx=0.376, rely=0.531, relwidth=0.129
                , relheight=0.0, height=18)
        self.CheckNorthAmericaLP.configure(variable=self.tch68)
        self.CheckNorthAmericaLP.configure(text='''Africa''')
        self.CheckNorthAmericaLP.configure(compound='left')

        self.CheckOceaniaLP = ttk.Checkbutton(self.FrameLP)
        self.CheckOceaniaLP.place(relx=0.657, rely=0.531, relwidth=0.152
                , relheight=0.0, height=18)
        self.CheckOceaniaLP.configure(variable=self.tch70)
        self.CheckOceaniaLP.configure(text='''Oceania''')
        self.CheckOceaniaLP.configure(compound='left')

        self.ScrolledwindowPreferencesLP = ScrolledWindow(self.FrameLP)
        self.ScrolledwindowPreferencesLP.place(relx=0.07, rely=0.623
                , relheight=0.273, relwidth=0.853)
        self.ScrolledwindowPreferencesLP.configure(background="#d9d9d9",
                borderwidth="2", highlightbackground="#d9d9d9",
                highlightcolor="#000000", insertbackground="#000000",
                relief="groove", selectbackground="#d9d9d9",
                selectforeground="black")
        self.color = self.ScrolledwindowPreferencesLP.cget("background")
        self.ScrolledwindowPreferencesLP_f = tk.Frame(self.ScrolledwindowPreferencesLP,
                            background=self.color)
        self.ScrolledwindowPreferencesLP.create_window(0, 0, anchor='nw',
                                           window=self.ScrolledwindowPreferencesLP_f)

        self.ButtonRankingLP = ttk.Button(self.FrameLP)
        self.ButtonRankingLP.place(relx=0.35, rely=0.914, height=46, width=125)
        self.ButtonRankingLP.configure(text='''Rank !''')
        self.ButtonRankingLP.configure(compound='left')

        self.FrameRBP = tk.Frame(self.BackgroundStudent)
        self.FrameRBP.place(relx=0.319, rely=0.683, relheight=0.281
                , relwidth=0.668)
        self.FrameRBP.configure(relief='groove', borderwidth="2",
                background="#d9d9d9", highlightbackground="#d9d9d9",
                highlightcolor="#000000")

        self.LabelUniNameRBP = tk.Label(self.FrameRBP)
        self.LabelUniNameRBP.place(relx=0.031, rely=0.085, height=21, width=352)
        self.LabelUniNameRBP.configure(activebackground="#d9d9d9",
                activeforeground="black", anchor='w', background="#d9d9d9",
                compound='left', disabledforeground="#a3a3a3",
                foreground="white", highlightbackground="#d9d9d9",
                highlightcolor="#000000", text='''University, City, Country''')

        self.FrameUniStatsRBP = tk.Frame(self.FrameRBP)
        self.FrameUniStatsRBP.place(relx=0.218, rely=0.256, relheight=0.658
                , relwidth=0.76)
        self.FrameUniStatsRBP.configure(relief='groove', borderwidth="2",
                background="#d9d9d9", cursor="fleur",
                highlightbackground="#d9d9d9", highlightcolor="#000000")

        self.LabelUniStats11 = tk.Label(self.FrameUniStatsRBP)
        self.LabelUniStats11.place(relx=0.014, rely=0.052, height=65, width=154)
        self.LabelUniStats11.configure(activebackground="#d9d9d9",
                activeforeground="black", anchor='w', background="#d9d9d9",
                compound='left', disabledforeground="#a3a3a3",
                foreground="white", highlightbackground="#d9d9d9",
                highlightcolor="#000000", text='''Ranking''')

        self.LabelUniStats21 = tk.Label(self.FrameUniStatsRBP)
        self.LabelUniStats21.place(relx=0.014, rely=0.552, height=65, width=155)
        self.LabelUniStats21.configure(activebackground="#d9d9d9",
                activeforeground="black", anchor='w', background="#d9d9d9",
                compound='left', disabledforeground="#a3a3a3",
                foreground="white", highlightbackground="#d9d9d9",
                highlightcolor="#000000", text='''Engineering Ranking''')

        self.LabelUniStats12 = tk.Label(self.FrameUniStatsRBP)
        self.LabelUniStats12.place(relx=0.259, rely=0.052, height=65, width=155)
        self.LabelUniStats12.configure(activebackground="#d9d9d9",
                activeforeground="black", anchor='w', background="#d9d9d9",
                compound='left', disabledforeground="#a3a3a3",
                foreground="white", highlightbackground="#d9d9d9",
                highlightcolor="#000000", text='''Cost of living''')

        self.LabelUniStats22 = tk.Label(self.FrameUniStatsRBP)
        self.LabelUniStats22.place(relx=0.259, rely=0.552, height=65, width=155)
        self.LabelUniStats22.configure(activebackground="#d9d9d9",
                activeforeground="black", anchor='w', background="#d9d9d9",
                compound='left', cursor="fleur", disabledforeground="#a3a3a3",
                foreground="white", highlightbackground="#d9d9d9",
                highlightcolor="#000000", text='''Weather''')

        self.LabelUniStats13 = tk.Label(self.FrameUniStatsRBP)
        self.LabelUniStats13.place(relx=0.503, rely=0.052, height=65, width=154)
        self.LabelUniStats13.configure(activebackground="#d9d9d9",
                activeforeground="black", anchor='w', background="#d9d9d9",
                compound='left', cursor="fleur", disabledforeground="#a3a3a3",
                foreground="white", highlightbackground="#d9d9d9",
                highlightcolor="#000000", text='''Nightlife''')

        self.LabelUniStats23 = tk.Label(self.FrameUniStatsRBP)
        self.LabelUniStats23.place(relx=0.503, rely=0.552, height=65, width=154)
        self.LabelUniStats23.configure(activebackground="#d9d9d9",
                activeforeground="black", anchor='w', background="#d9d9d9",
                compound='left', cursor="fleur", disabledforeground="#a3a3a3",
                foreground="white", highlightbackground="#d9d9d9",
                highlightcolor="#000000", text='''Previous cutoff grade''')

        self.LabelUniStats14 = tk.Label(self.FrameUniStatsRBP)
        self.LabelUniStats14.place(relx=0.748, rely=0.052, height=65, width=154)
        self.LabelUniStats14.configure(activebackground="#d9d9d9",
                activeforeground="black", anchor='w', background="#d9d9d9",
                compound='left', cursor="fleur", disabledforeground="#a3a3a3",
                foreground="white", highlightbackground="#d9d9d9",
                highlightcolor="#000000", text='''Available spots''')

        self.LabelUniStats24 = tk.Label(self.FrameUniStatsRBP)
        self.LabelUniStats24.place(relx=0.748, rely=0.552, height=65, width=155)
        self.LabelUniStats24.configure(activebackground="#d9d9d9",
                activeforeground="black", anchor='w', background="#d9d9d9",
                compound='left', cursor="fleur", disabledforeground="#a3a3a3",
                foreground="white", highlightbackground="#d9d9d9",
                highlightcolor="#000000", text='''Duration''')

        self.ImageLogoRBP = tk.Label(self.FrameRBP)
        self.ImageLogoRBP.place(relx=0.024, rely=0.239, height=160, width=160)
        self.ImageLogoRBP.configure(activebackground="#c8102e",
                activeforeground="#c8102e", anchor='w', background="#d9d9d9",
                compound='left', disabledforeground="#a3a3a3",
                foreground="white", highlightbackground="#d9d9d9",
                highlightcolor="#000000", text='''University LOGO (image)''')

        self.StudentMapButton = ttk.Button(self.FrameRBP)
        self.StudentMapButton.place(relx=0.913, rely=0.085, height=26, width=65)
        self.StudentMapButton.configure(takefocus="")
        self.StudentMapButton.configure(text='''Map''')
        self.StudentMapButton.configure(compound='left')

        self.StudentWebButton = ttk.Button(self.FrameRBP)
        self.StudentWebButton.place(relx=0.83, rely=0.085, height=26, width=65)
        self.StudentWebButton.configure(takefocus="")
        self.StudentWebButton.configure(text='''Website''')
        self.StudentWebButton.configure(compound='left')

        self.ScrolledwindowRUP = ScrolledWindow(self.BackgroundStudent)
        self.ScrolledwindowRUP.place(relx=0.319, rely=0.06, relheight=0.606
                , relwidth=0.668)
        self.ScrolledwindowRUP.configure(background="#d9d9d9",
                borderwidth="2", highlightbackground="#d9d9d9",
                highlightcolor="#000000", insertbackground="#000000",
                relief="groove", selectbackground="#d9d9d9",
                selectforeground="black")
        self.color = self.ScrolledwindowRUP.cget("background")
        self.ScrolledwindowRUP_f = tk.Frame(self.ScrolledwindowRUP,
                            background=self.color)
        self.ScrolledwindowRUP.create_window(0, 0, anchor='nw',
                                           window=self.ScrolledwindowRUP_f)

        self.BackgroundLogin = tk.Frame(self.top)
        self.BackgroundLogin.place(relx=0.0, rely=0.0, relheight=1.006
                , relwidth=1.003)
        self.BackgroundLogin.configure(relief='groove', borderwidth="2",
                background="#c8102e", highlightbackground="#d9d9d9",
                highlightcolor="#000000")

        self.LoginLabelFrame = tk.LabelFrame(self.BackgroundLogin)
        self.LoginLabelFrame.place(relx=0.312, rely=0.466, relheight=0.388
                , relwidth=0.382)
        self.LoginLabelFrame.configure(relief='groove', foreground="white",
                text='''Student''', background="#c8102e",
                highlightbackground="#d9d9d9", highlightcolor="#000000")

        self.LoginMailLabel = ttk.Label(self.LoginLabelFrame)
        self.LoginMailLabel.place(relx=0.181, rely=0.216, height=17, width=34
                , bordermode='ignore')
        self.LoginMailLabel.configure(font="TkDefaultFont", relief="flat",
                text='''Email:''', compound='left')

        self.LoginMailEntry = ttk.Entry(self.LoginLabelFrame)
        self.LoginMailEntry.place(relx=0.181, rely=0.278, relheight=0.065
                , relwidth=0.646, bordermode='ignore')
        self.LoginMailEntry.configure(exportselection="0", cursor="ibeam")

        self.LoginPasswordLabel = ttk.Label(self.LoginLabelFrame)
        self.LoginPasswordLabel.place(relx=0.181, rely=0.432, height=17, width=64
                , bordermode='ignore')
        self.LoginPasswordLabel.configure(font="TkDefaultFont", relief="flat",
                text='''Password:''', compound='left')

        self.LoginPasswordEntry = ttk.Entry(self.LoginLabelFrame)
        self.LoginPasswordEntry.place(relx=0.181, rely=0.494, relheight=0.065
                , relwidth=0.646, bordermode='ignore')
        self.LoginPasswordEntry.configure(exportselection="0", cursor="ibeam")

        self.LoginSingupButton = ttk.Button(self.LoginLabelFrame)
        self.LoginSingupButton.place(relx=0.606, rely=0.772, height=56, width=125
                , bordermode='ignore')
        self.LoginSingupButton.configure(text='''Tbutton''')
        self.LoginSingupButton.configure(compound='left')

        self.LoginLoginButton = ttk.Button(self.LoginLabelFrame)
        self.LoginLoginButton.place(relx=0.178, rely=0.772, height=56, width=125
                , bordermode='ignore')
        self.LoginLoginButton.configure(text='''Tbutton''')
        self.LoginLoginButton.configure(compound='left')

        self.LoginAdminLoginButton = ttk.Button(self.LoginLabelFrame)
        self.LoginAdminLoginButton.place(relx=0.392, rely=0.772, height=56
                , width=125, bordermode='ignore')
        self.LoginAdminLoginButton.configure(text='''Tbutton''')
        self.LoginAdminLoginButton.configure(compound='left')

        self.LoginTitle = tk.Label(self.BackgroundLogin)
        self.LoginTitle.place(relx=0.284, rely=0.18, height=91, width=644)
        self.LoginTitle.configure(activebackground="#d9d9d9",
                activeforeground="black", anchor='w', background="#c8102e",
                compound='left', disabledforeground="#a3a3a3",
                font="-family {Microsoft YaHei} -size 48 -weight bold",
                foreground="#ffffff", highlightbackground="#d9d9d9",
                highlightcolor="#000000", text='''UPF Mobility Agent''')

        self.LoginAdminButton = ttk.Button(self.BackgroundLogin)
        self.LoginAdminButton.place(relx=0.54, rely=0.323, height=86, width=125)
        self.LoginAdminButton.configure(text='''Admin''')
        self.LoginAdminButton.configure(compound='left')

        self.LoginStudentButton = ttk.Button(self.BackgroundLogin)
        self.LoginStudentButton.place(relx=0.388, rely=0.323, height=86
                , width=125)
        self.LoginStudentButton.configure(text='''Student''')
        self.LoginStudentButton.configure(compound='left')
        self.LoginStudentButton.configure(cursor="fleur")

        self.BackgroundAdmin = tk.Frame(self.top)
        self.BackgroundAdmin.place(relx=0.0, rely=0.0, relheight=1.006
                , relwidth=1.003)
        self.BackgroundAdmin.configure(relief='groove', borderwidth="2",
                background="#c8102e", highlightbackground="#d9d9d9",
                highlightcolor="#000000")

        self.AdminFrame = tk.Frame(self.BackgroundAdmin)
        self.AdminFrame.place(relx=0.017, rely=0.066, relheight=0.903
                , relwidth=0.967)
        self.AdminFrame.configure(relief='groove', borderwidth="2",
                background="#d9d9d9", highlightbackground="#d9d9d9",
                highlightcolor="#000000")

        self.AdminEditDeleteButton = ttk.Button(self.AdminFrame)
        self.AdminEditDeleteButton.place(relx=0.028, rely=0.224, height=86
                , width=275)
        self.AdminEditDeleteButton.configure(takefocus="")
        self.AdminEditDeleteButton.configure(text='''Edit / Delete''')
        self.AdminEditDeleteButton.configure(compound='left')

        self.AdminAddButton = ttk.Button(self.AdminFrame)
        self.AdminAddButton.place(relx=0.029, rely=0.598, height=86, width=275)
        self.AdminAddButton.configure(takefocus="")
        self.AdminAddButton.configure(text='''Add''')
        self.AdminAddButton.configure(compound='left')
        self.AdminAddButton.configure(cursor="fleur")

        self.AdminUniSpinbox = ttk.Spinbox(self.AdminFrame, from_=1, to=100)
        self.AdminUniSpinbox.place(relx=0.028, rely=0.345, relheight=0.027
                , relwidth=0.198)
        self.AdminUniSpinbox.configure(exportselection="0")
        self.AdminUniSpinbox.configure(background="white")
        self.AdminUniSpinbox.configure(takefocus="")

        self.AdminTitle = ttk.Label(self.AdminFrame)
        self.AdminTitle.place(relx=0.014, rely=0.027, height=28, width=143)
        self.AdminTitle.configure(font="TkDefaultFont", relief="flat",
                text='''Admin Settings''', compound='left')

        self.AdminFrameEntries = ttk.Frame(self.AdminFrame)
        self.AdminFrameEntries.place(relx=0.244, rely=0.027, relheight=0.948
                , relwidth=0.741)
        self.AdminFrameEntries.configure(relief='groove', borderwidth="2",
                cursor="fleur")

        self.AdminNameLabel = ttk.Label(self.AdminFrameEntries)
        self.AdminNameLabel.place(relx=0.058, rely=0.07, height=17, width=86)
        self.AdminNameLabel.configure(font="TkDefaultFont", relief="flat",
                text='''Name''', compound='left', cursor="fleur")

        self.AdminIDLabel = ttk.Label(self.AdminFrameEntries)
        self.AdminIDLabel.place(relx=0.058, rely=0.196, height=17, width=117)
        self.AdminIDLabel.configure(font="TkDefaultFont", relief="flat",
                text='''ID''', compound='left')

        self.AdminCountryLabel = ttk.Label(self.AdminFrameEntries)
        self.AdminCountryLabel.place(relx=0.058, rely=0.322, height=17, width=86)
        self.AdminCountryLabel.configure(font="TkDefaultFont", relief="flat",
                text='''Country''', compound='left')

        self.AdminCityLabel = ttk.Label(self.AdminFrameEntries)
        self.AdminCityLabel.place(relx=0.058, rely=0.448, height=18, width=117)
        self.AdminCityLabel.configure(font="TkDefaultFont", relief="flat",
                text='''City''', compound='left')

        self.AdminContinentLabel = ttk.Label(self.AdminFrameEntries)
        self.AdminContinentLabel.place(relx=0.058, rely=0.573, height=17
                , width=165)
        self.AdminContinentLabel.configure(font="TkDefaultFont", relief="flat",
                text='''Continent''', compound='left')

        self.AdminMinimumGradeLabel = ttk.Label(self.AdminFrameEntries)
        self.AdminMinimumGradeLabel.place(relx=0.058, rely=0.699, height=17
                , width=164)
        self.AdminMinimumGradeLabel.configure(font="TkDefaultFont", relief="flat",
                text='''Minimum grade''', compound='left')

        self.AdminWebsiteLabel = ttk.Label(self.AdminFrameEntries)
        self.AdminWebsiteLabel.place(relx=0.058, rely=0.825, height=17, width=85)
        self.AdminWebsiteLabel.configure(font="TkDefaultFont", relief="flat",
                text='''Website''', compound='left')

        self.AdminLatitudeLabel = ttk.Label(self.AdminFrameEntries)
        self.AdminLatitudeLabel.place(relx=0.358, rely=0.07, height=17, width=86)
        self.AdminLatitudeLabel.configure(font="TkDefaultFont", relief="flat",
                text='''Latitude''', compound='left')

        self.AdminLongitudeLabel = ttk.Label(self.AdminFrameEntries)
        self.AdminLongitudeLabel.place(relx=0.358, rely=0.196, height=17
                , width=117)
        self.AdminLongitudeLabel.configure(font="TkDefaultFont", relief="flat",
                text='''Longitude''', compound='left', cursor="fleur")

        self.AdminLanguagesLabel = ttk.Label(self.AdminFrameEntries)
        self.AdminLanguagesLabel.place(relx=0.358, rely=0.322, height=17
                , width=198)
        self.AdminLanguagesLabel.configure(font="TkDefaultFont", relief="flat",
                text='''Languages required''', compound='left')

        self.AdminSpotsLabel = ttk.Label(self.AdminFrameEntries)
        self.AdminSpotsLabel.place(relx=0.358, rely=0.797, height=17, width=94)
        self.AdminSpotsLabel.configure(font="TkDefaultFont", relief="flat",
                text='''Spots available''', compound='left')

        self.AdminRankLabel = tk.Label(self.AdminFrameEntries)
        self.AdminRankLabel.place(relx=0.667, rely=0.07, height=21, width=113)
        self.AdminRankLabel.configure(activebackground="#d9d9d9",
                activeforeground="black", anchor='w', background="#d9d9d9",
                compound='left', disabledforeground="#a3a3a3",
                foreground="#000000", highlightbackground="#d9d9d9",
                highlightcolor="#000000", text='''University Ranking''')

        self.AdminRankEngLabel = tk.Label(self.AdminFrameEntries)
        self.AdminRankEngLabel.place(relx=0.667, rely=0.196, height=21
                , width=124)
        self.AdminRankEngLabel.configure(activebackground="#d9d9d9",
                activeforeground="black", anchor='w', background="#d9d9d9",
                compound='left', disabledforeground="#a3a3a3",
                foreground="#000000", highlightbackground="#d9d9d9",
                highlightcolor="#000000", text='''Engineering Ranking''')

        self.AdminWeatherLabel = tk.Label(self.AdminFrameEntries)
        self.AdminWeatherLabel.place(relx=0.667, rely=0.322, height=21, width=53)
        self.AdminWeatherLabel.configure(activebackground="#d9d9d9",
                activeforeground="black", anchor='w', background="#d9d9d9",
                compound='left', cursor="fleur", disabledforeground="#a3a3a3",
                foreground="#000000", highlightbackground="#d9d9d9",
                highlightcolor="#000000", text='''Weather''')

        self.AdminNightlifeLabel = tk.Label(self.AdminFrameEntries)
        self.AdminNightlifeLabel.place(relx=0.667, rely=0.448, height=21
                , width=49)
        self.AdminNightlifeLabel.configure(activebackground="#d9d9d9",
                activeforeground="black", anchor='w', background="#d9d9d9",
                compound='left', disabledforeground="#a3a3a3",
                foreground="#000000", highlightbackground="#d9d9d9",
                highlightcolor="#000000", text='''Nightlife''')

        self.AdminCostLabel = tk.Label(self.AdminFrameEntries)
        self.AdminCostLabel.place(relx=0.667, rely=0.573, height=20, width=124)
        self.AdminCostLabel.configure(activebackground="#d9d9d9",
                activeforeground="black", anchor='w', background="#d9d9d9",
                compound='left', disabledforeground="#a3a3a3",
                foreground="#000000", highlightbackground="#d9d9d9",
                highlightcolor="#000000", text='''Cost of living''')

        self.AdminCutoffLabel = tk.Label(self.AdminFrameEntries)
        self.AdminCutoffLabel.place(relx=0.667, rely=0.699, height=21, width=134)
        self.AdminCutoffLabel.configure(activebackground="#d9d9d9",
                activeforeground="black", anchor='w', background="#d9d9d9",
                compound='left', disabledforeground="#a3a3a3",
                foreground="#000000", highlightbackground="#d9d9d9",
                highlightcolor="#000000", text='''Previous cutoff grade''')

        self.AdminDurationLabel = tk.Label(self.AdminFrameEntries)
        self.AdminDurationLabel.place(relx=0.667, rely=0.797, height=21
                , width=104)
        self.AdminDurationLabel.configure(activebackground="#d9d9d9",
                activeforeground="black", anchor='w', background="#d9d9d9",
                compound='left', disabledforeground="#a3a3a3",
                foreground="#000000", highlightbackground="#d9d9d9",
                highlightcolor="#000000", text='''Duration (months)''')

        self.AdminNameEntry = ttk.Entry(self.AdminFrameEntries)
        self.AdminNameEntry.place(relx=0.058, rely=0.098, relheight=0.029
                , relwidth=0.248)
        self.AdminNameEntry.configure(exportselection="0", cursor="ibeam")

        self.AdminIDEntry = ttk.Entry(self.AdminFrameEntries)
        self.AdminIDEntry.place(relx=0.058, rely=0.224, relheight=0.029
                , relwidth=0.248)
        self.AdminIDEntry.configure(exportselection="0", cursor="ibeam")

        self.AdminCountryEntry = ttk.Entry(self.AdminFrameEntries)
        self.AdminCountryEntry.place(relx=0.058, rely=0.35, relheight=0.029
                , relwidth=0.248)
        self.AdminCountryEntry.configure(exportselection="0", cursor="ibeam")

        self.AdminCityEntry = ttk.Entry(self.AdminFrameEntries)
        self.AdminCityEntry.place(relx=0.058, rely=0.476, relheight=0.029
                , relwidth=0.248)
        self.AdminCityEntry.configure(exportselection="0", cursor="ibeam")

        self.AdminContinentEntry = ttk.Entry(self.AdminFrameEntries)
        self.AdminContinentEntry.place(relx=0.058, rely=0.601, relheight=0.028
                , relwidth=0.248)
        self.AdminContinentEntry.configure(exportselection="0", cursor="ibeam")

        self.AdminGradeEntry = ttk.Entry(self.AdminFrameEntries)
        self.AdminGradeEntry.place(relx=0.058, rely=0.727, relheight=0.028
                , relwidth=0.248)
        self.AdminGradeEntry.configure(exportselection="0", cursor="ibeam")

        self.AdminWebsiteEntry = ttk.Entry(self.AdminFrameEntries)
        self.AdminWebsiteEntry.place(relx=0.058, rely=0.853, relheight=0.029
                , relwidth=0.248)
        self.AdminWebsiteEntry.configure(exportselection="0", cursor="ibeam")

        self.AdminLatitudeEntry = ttk.Entry(self.AdminFrameEntries)
        self.AdminLatitudeEntry.place(relx=0.358, rely=0.098, relheight=0.029
                , relwidth=0.257)
        self.AdminLatitudeEntry.configure(exportselection="0", cursor="fleur")

        self.AdminLongitudeEntry = ttk.Entry(self.AdminFrameEntries)
        self.AdminLongitudeEntry.place(relx=0.358, rely=0.224, relheight=0.029
                , relwidth=0.257)
        self.AdminLongitudeEntry.configure(exportselection="0", cursor="ibeam")

        self.AdminSpotsScale =  tk.Scale(self.AdminFrameEntries, from_=0.0, to=100.0, resolution=1.0)
        self.AdminSpotsScale.place(relx=0.358, rely=0.825, relheight=0.059
                , relwidth=0.258)
        self.AdminSpotsScale.configure(activebackground="#d9d9d9",
                background="#d9d9d9", foreground="#000000",
                highlightbackground="#d9d9d9", highlightcolor="#000000",
                length="267", orient="horizontal", troughcolor="#c4c4c4")

        self.AdminRankEntry = ttk.Entry(self.AdminFrameEntries)
        self.AdminRankEntry.place(relx=0.667, rely=0.098, relheight=0.029
                , relwidth=0.257)
        self.AdminRankEntry.configure(exportselection="0", takefocus="",
                cursor="ibeam")

        self.AdminEngRankEntry = ttk.Entry(self.AdminFrameEntries)
        self.AdminEngRankEntry.place(relx=0.667, rely=0.224, relheight=0.029
                , relwidth=0.257)
        self.AdminEngRankEntry.configure(exportselection="0", takefocus="",
                cursor="ibeam")

        self.AdminWeatherEntry = ttk.Entry(self.AdminFrameEntries)
        self.AdminWeatherEntry.place(relx=0.667, rely=0.35, relheight=0.029
                , relwidth=0.257)
        self.AdminWeatherEntry.configure(exportselection="0", takefocus="",
                cursor="ibeam")

        self.AdminCostScale =  tk.Scale(self.AdminFrameEntries, from_=0.0, to=100.0, resolution=1.0)
        self.AdminCostScale.place(relx=0.667, rely=0.601, relheight=0.059
                , relwidth=0.256)
        self.AdminCostScale.configure(activebackground="#d9d9d9",
                background="#d9d9d9", foreground="#000000",
                highlightbackground="#d9d9d9", highlightcolor="#000000",
                length="266", orient="horizontal", troughcolor="#c4c4c4")

        self.AdminCutoffEntry = ttk.Entry(self.AdminFrameEntries)
        self.AdminCutoffEntry.place(relx=0.667, rely=0.727, relheight=0.029
                , relwidth=0.257)
        self.AdminCutoffEntry.configure(exportselection="0", takefocus="",
                cursor="ibeam")

        self.AdminDurationScale =  tk.Scale(self.AdminFrameEntries, from_=0.0, to=100.0, resolution=1.0)
        self.AdminDurationScale.place(relx=0.667, rely=0.825, relheight=0.059
                , relwidth=0.256)
        self.AdminDurationScale.configure(activebackground="#d9d9d9",
                background="#d9d9d9", foreground="#000000",
                highlightbackground="#d9d9d9", highlightcolor="#000000",
                length="266", orient="horizontal", troughcolor="#c4c4c4")

        self.AdminLanguagesFrame = ttk.Frame(self.AdminFrameEntries)
        self.AdminLanguagesFrame.place(relx=0.358, rely=0.35, relheight=0.401
                , relwidth=0.259)
        self.AdminLanguagesFrame.configure(relief='groove', borderwidth="2")

        self.AdminSaveButton = tk.Button(self.AdminFrameEntries)
        self.AdminSaveButton.place(relx=0.909, rely=0.923, height=36, width=67)
        self.AdminSaveButton.configure(activebackground="#d9d9d9",
                activeforeground="black", background="#d9d9d9",
                compound='left', disabledforeground="#a3a3a3",
                foreground="#000000", highlightbackground="#d9d9d9",
                highlightcolor="#000000", text='''Delete''')

        self.AdminNightlifeScale =  tk.Scale(self.AdminFrameEntries, from_=0.0, to=100.0, resolution=1.0)
        self.AdminNightlifeScale.place(relx=0.667, rely=0.476, relheight=0.06
                , relwidth=0.255)
        self.AdminNightlifeScale.configure(activebackground="#d9d9d9",
                background="#d9d9d9", foreground="#000000",
                highlightbackground="#d9d9d9", highlightcolor="#000000",
                length="266", orient="horizontal", troughcolor="#c4c4c4")

        self.AdminDeleteLittleButton = tk.Button(self.AdminFrameEntries)
        self.AdminDeleteLittleButton.place(relx=0.822, rely=0.923, height=36
                , width=67)
        self.AdminDeleteLittleButton.configure(activebackground="#d9d9d9",
                activeforeground="black", background="#d9d9d9",
                compound='left', disabledforeground="#a3a3a3",
                foreground="#000000", highlightbackground="#d9d9d9",
                highlightcolor="#000000", text='''Save''')

        self.FrameMenuBar_1 = tk.Frame(self.BackgroundAdmin)
        self.FrameMenuBar_1.place(relx=0.0, rely=0.0, relheight=0.042
                , relwidth=1.001)
        self.FrameMenuBar_1.configure(relief='groove', borderwidth="2",
                background="#d9d9d9", highlightbackground="#d9d9d9",
                highlightcolor="#000000")

        self.AdminHelpButton = tk.Button(self.FrameMenuBar_1)
        self.AdminHelpButton.place(relx=0.947, rely=0.114, height=26, width=47)
        self.AdminHelpButton.configure(activebackground="#d9d9d9",
                activeforeground="black", background="#d9d9d9",
                compound='left', cursor="fleur", disabledforeground="#a3a3a3",
                foreground="white", highlightbackground="#d9d9d9",
                highlightcolor="#000000", text='''Help''')

        self.AdminLogoutButton = tk.Button(self.FrameMenuBar_1)
        self.AdminLogoutButton.place(relx=0.013, rely=0.143, height=26, width=47)
        self.AdminLogoutButton.configure(activebackground="#d9d9d9",
                activeforeground="black", background="#d9d9d9",
                compound='left', disabledforeground="#a3a3a3",
                foreground="white", highlightbackground="#d9d9d9",
                highlightcolor="#000000", text='''Log out''')

# The following code is added to facilitate the Scrolled widgets you specified.
class AutoScroll(object):
    '''Configure the scrollbars for a widget.'''
    def __init__(self, master):
        #  Rozen. Added the try-except clauses so that this class
        #  could be used for scrolled entry widget for which vertical
        #  scrolling is not supported. 5/7/14.
        try:
            vsb = ttk.Scrollbar(master, orient='vertical', command=self.yview)
        except:
            pass
        hsb = ttk.Scrollbar(master, orient='horizontal', command=self.xview)
        try:
            self.configure(yscrollcommand=self._autoscroll(vsb))
        except:
            pass
        self.configure(xscrollcommand=self._autoscroll(hsb))
        self.grid(column=0, row=0, sticky='nsew')
        try:
            vsb.grid(column=1, row=0, sticky='ns')
        except:
            pass
        hsb.grid(column=0, row=1, sticky='ew')
        master.grid_columnconfigure(0, weight=1)
        master.grid_rowconfigure(0, weight=1)
        # Copy geometry methods of master  (taken from ScrolledText.py)
        methods = tk.Pack.__dict__.keys() | tk.Grid.__dict__.keys() \
                  | tk.Place.__dict__.keys()
        for meth in methods:
            if meth[0] != '_' and meth not in ('config', 'configure'):
                setattr(self, meth, getattr(master, meth))

    @staticmethod
    def _autoscroll(sbar):
        '''Hide and show scrollbar as needed.'''
        def wrapped(first, last):
            first, last = float(first), float(last)
            if first <= 0 and last >= 1:
                sbar.grid_remove()
            else:
                sbar.grid()
            sbar.set(first, last)
        return wrapped

    def __str__(self):
        return str(self.master)

def _create_container(func):
    '''Creates a ttk Frame with a given master, and use this new frame to
    place the scrollbars and the widget.'''
    def wrapped(cls, master, **kw):
        container = ttk.Frame(master)
        container.bind('<Enter>', lambda e: _bound_to_mousewheel(e, container))
        container.bind('<Leave>', lambda e: _unbound_to_mousewheel(e, container))
        return func(cls, container, **kw)
    return wrapped

class ScrolledWindow(AutoScroll, tk.Canvas):
    '''A standard Tkinter Canvas widget with scrollbars that will
    automatically show/hide as needed.'''
    @_create_container
    def __init__(self, master, **kw):
        tk.Canvas.__init__(self, master, **kw)
        AutoScroll.__init__(self, master)

import platform
def _bound_to_mousewheel(event, widget):
    child = widget.winfo_children()[0]
    if platform.system() == 'Windows' or platform.system() == 'Darwin':
        child.bind_all('<MouseWheel>', lambda e: _on_mousewheel(e, child))
        child.bind_all('<Shift-MouseWheel>', lambda e: _on_shiftmouse(e, child))
    else:
        child.bind_all('<Button-4>', lambda e: _on_mousewheel(e, child))
        child.bind_all('<Button-5>', lambda e: _on_mousewheel(e, child))
        child.bind_all('<Shift-Button-4>', lambda e: _on_shiftmouse(e, child))
        child.bind_all('<Shift-Button-5>', lambda e: _on_shiftmouse(e, child))

def _unbound_to_mousewheel(event, widget):
    if platform.system() == 'Windows' or platform.system() == 'Darwin':
        widget.unbind_all('<MouseWheel>')
        widget.unbind_all('<Shift-MouseWheel>')
    else:
        widget.unbind_all('<Button-4>')
        widget.unbind_all('<Button-5>')
        widget.unbind_all('<Shift-Button-4>')
        widget.unbind_all('<Shift-Button-5>')

def _on_mousewheel(event, widget):
    if platform.system() == 'Windows':
        widget.yview_scroll(-1*int(event.delta/120),'units')
    elif platform.system() == 'Darwin':
        widget.yview_scroll(-1*int(event.delta),'units')
    else:
        if event.num == 4:
            widget.yview_scroll(-1, 'units')
        elif event.num == 5:
            widget.yview_scroll(1, 'units')

def _on_shiftmouse(event, widget):
    if platform.system() == 'Windows':
        widget.xview_scroll(-1*int(event.delta/120), 'units')
    elif platform.system() == 'Darwin':
        widget.xview_scroll(-1*int(event.delta), 'units')
    else:
        if event.num == 4:
            widget.xview_scroll(-1, 'units')
        elif event.num == 5:
            widget.xview_scroll(1, 'units')
def start_up():
    GUI_support.main()

if __name__ == '__main__':
    GUI_support.main()




