#! /usr/bin/env python3
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 8.1
#  in conjunction with Tcl version 8.6
#    Jan 19, 2026 05:50:00 PM CET  platform: Windows NT

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *
from tkinter import messagebox

import GUI
from MobilityManager import MobilityManager

# ! /usr/bin/env python3
#  -*- coding: utf-8 -*-

import sys
import tkinter as tk
import GUI
from utilities import Utilities
from GUI_logic import *

def main(*args):
    '''Main entry point for the application.'''
    global root, _top1, _w1
    root = tk.Tk()
    root.protocol('WM_DELETE_WINDOW', root.destroy)

    # Initialize the GUI class
    _top1 = root
    _w1 = GUI.FrameBP(_top1)

    mobility_manager = MobilityManager("data/entries.csv")
    mobility_manager.load_universities()
    mobility_manager.load_users()
    _w1.AD_uni_combobox['values'] = mobility_manager.get_university_names()


    _w1.AD_editdelete_button.configure(command=lambda: admin_editdelete(_w1=_w1, mobility_manager=mobility_manager))    
    _w1.AD_add_button.configure(command=lambda: clear_admin_entries(_w1=_w1))


    _w1.AD_save_button.configure(command=lambda: save_admin_entries(_w1=_w1, mobility_manager=mobility_manager))
    _w1.AD_delete_button.configure(command=lambda: delete_admin_entries(_w1=_w1, mobility_manager=mobility_manager))

    
    _w1.AD_uni_combobox.bind('<<ComboboxSelected>>', lambda e: check_uni_selection(_w1=_w1))

    # Link Login Screen Buttons
    _w1.LG_student_button.configure(command=lambda: show_student_login(_w1=_w1, root=root))
    _w1.LG_admin_button.configure(command=lambda: show_admin_login(_w1=_w1, root=root))

    # --- Authentication button handlers ---

    # Bind the auth button handlers
    _w1.LG_adminlogin_button.configure(command=lambda: admin_login_action(_w1=_w1, mobility_manager=mobility_manager))
    _w1.LG_studentlogin_button.configure(command=lambda: student_login_action(_w1=_w1, mobility_manager=mobility_manager))
    _w1.LG_studentsingup_button.configure(command=lambda: student_signup_action(_w1=_w1, mobility_manager=mobility_manager))

    # Link Logout Buttons
    _w1.ST_logout_button.configure(command=lambda: logout(_w1=_w1, root=root))
    _w1.AD_logout_button.configure(command=lambda: logout(_w1=_w1, root=root))

    # Set the initial view to the Login screen
    show_login(_w1=_w1, root=root)
    check_uni_selection(_w1=_w1)

    root.mainloop()

if __name__ == '__main__':
    GUI.start_up()
    
