#! /usr/bin/env python3
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 8.1
#  in conjunction with Tcl version 8.6
#    Jan 19, 2026 05:50:00 PM CET  platform: Windows NT

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *

import GUI

# ! /usr/bin/env python3
#  -*- coding: utf-8 -*-

import sys
import tkinter as tk
import GUI


def main(*args):
    '''Main entry point for the application.'''
    global root, _top1, _w1
    root = tk.Tk()
    root.protocol('WM_DELETE_WINDOW', root.destroy)

    # Initialize the GUI class
    _top1 = root
    _w1 = GUI.FrameBP(_top1)

    # --- NAVIGATION LOGIC ---

    def show_student():
        _w1.BackgroundStudent.lift()

    def show_admin():
        _w1.BackgroundAdmin.lift()

    def show_login():
        _w1.BackgroundLogin.lift()

    # Link Login Screen Buttons
    _w1.LoginStudentButton.configure(command=show_student)
    _w1.LoginAdminButton.configure(command=show_admin)

    # Link Logout Buttons
    _w1.StudentLogoutButton.configure(command=show_login)
    _w1.AdminLogoutButton.configure(command=show_login)

    # Set the initial view to the Login screen
    show_login()

    root.mainloop()


if __name__ == '__main__':
    GUI.start_up()




